[package]
edition = "2021"
name = "rust_tetris"
version = "0.1.0"

[dependencies]
# remove dynamic feature when release
# bevy = { version = "0.6.0", features = ["dynamic"] }
bevy = "0.6.0"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1