
pub const BLOCK_SIZE: u32 = 30;
pub const WIDTH_BLOCKS_COUNT: u32 = 12;
pub const HEIGHT_BLOCKS_COUNT: u32 = 23;

pub const INNER_HIGHT: u32 = BLOCK_SIZE * HEIGHT_BLOCKS_COUNT;
pub const INNER_WIDTH: u32 = BLOCK_SIZE * WIDTH_BLOCKS_COUNT;

pub const MOVE_BETWEEN_MILLISECOND: u128 = 100;
pub const POLL_EVENT_INTERVAL_MILLISECOND: u64 = 10;
